sudo: required
dist: trusty
language: python

matrix:
    include:
        - python: 3.6
          env: KERAS_VERSION=2.2.4
        - python: 3.6
          env: SM_FRAMEWORK='tf.keras'

git:
  submodules: true


install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest pandas
  - source activate test-environment
  - pip install --only-binary=numpy,scipy numpy nose scipy matplotlib h5py theano


  # set library path
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH
  - conda install mkl mkl-service

  # install TensorFlow (CPU version).
  - pip install tensorflow==1.14

  # install keras
  - if [ -z $KERAS_VERSION ]; then
      echo "Using tf.keras";
    else
      echo "Using keras";
      pip install keras==$KERAS_VERSION;
    fi

  # install lib in develop mode
  - pip install -e .[tests]

  # permanent fixes #TODO: remove
  - pip install -U git+https://github.com/qubvel/classification_models@feature/tf.keras
  - pip install -U git+https://github.com/qubvel/efficientnet

  # detect one of markdown files is changed or not
  - export DOC_ONLY_CHANGED=False;
  - if [ $(git diff --name-only HEAD~1 | wc -l) == "1" ] && [[ "$(git diff --name-only HEAD~1)" == *"md" ]]; then
      export DOC_ONLY_CHANGED=True;
    fi

# command to run tests
script:
  - export MKL_THREADING_LAYER="GNU"
  - mkdir ~/.keras/models
  # set up keras backend
  - if [[ "$DOC_ONLY_CHANGED" == "False" ]]; then
        PYTHONPATH=$PWD:$PYTHONPATH py.test tests/;
    fi